

datasets:
  instruct_blip_llava_vig_eval:
    data_type: images
    build_info:
#      annotation: /mnt/petrelfs/share_data/zhonghuaping.p/datasets/LLaVA/process/complex_reasoning_77k_cocoformat.json
      images: /mnt/petrelfs/share_data/zhaozhiyuan/llava-150k/
      annotation: /mnt/petrelfs/hanxiao/working/llava_process/llava_val.json
